import React, {Component} from 'react';

export const Home = () => (
      <div>
     <h2>Home</h2>
     <p>A 180-page manifesto, Balotelli’s antics, Gerrard’s unrest and beyond. The inside story of Brendan Rodgers' time as Liverpool manager.A 180-page manifesto, Balotelli’s antics, Gerrard’s unrest and beyond. The inside story of Brendan Rodgers' time as Liverpool manager.A 180-page manifesto, Balotelli’s antics, Gerrard’s unrest and beyond. The inside story of Brendan Rodgers' time as Liverpool manager.A 180-page manifesto, Balotelli’s antics, Gerrard’s unrest and beyond. The inside story of Brendan Rodgers' time as Liverpool manager.A 180-page manifesto, Balotelli’s antics, Gerrard’s unrest and beyond. The inside story of Brendan Rodgers' time as Liverpool manager.A 180-page manifesto, Balotelli’s antics, Gerrard’s unrest and beyond. The inside story of Brendan Rodgers' time as Liverpool manager.A 180-page manifesto, Balotelli’s antics, Gerrard’s unrest and beyond. The inside story of Brendan Rodgers' time as Liverpool manager.A 180-page manifesto, Balotelli’s antics, Gerrard’s unrest and beyond. The inside story of Brendan Rodgers' time as Liverpool manager.A 180-page manifesto, Balotelli’s antics, Gerrard’s unrest and beyond. The inside story of Brendan Rodgers' time as Liverpool manager.A 180-page manifesto, Balotelli’s antics, Gerrard’s unrest and beyond. The inside story of Brendan Rodgers' time as Liverpool manager.A 180-page manifesto, Balotelli’s antics, Gerrard’s unrest and beyond. The inside story of Brendan Rodgers' time as Liverpool manager.A 180-page manifesto, Balotelli’s antics, Gerrard’s unrest and beyond. The inside story of Brendan Rodgers' time as Liverpool manager.A 180-page manifesto, Balotelli’s antics, Gerrard’s unrest and beyond. The inside story of Brendan Rodgers' time as Liverpool manager.A 180-page manifesto, Balotelli’s antics, Gerrard’s unrest and beyond. The inside story of Brendan Rodgers' time as Liverpool manager.A 180-page manifesto, Balotelli’s antics, Gerrard’s unrest and beyond. The inside story of Brendan Rodgers' time as Liverpool manager.A 180-page manifesto, Balotelli’s antics, Gerrard’s unrest and beyond. The inside story of Brendan Rodgers' time as Liverpool manager.A 180-page manifesto, Balotelli’s antics, Gerrard’s unrest and beyond. The inside story of Brendan Rodgers' time as Liverpool manager.</p>
     <p> home home home home </p>
     </div>
    )
